// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Vendorea.PartnerConnect.Persistence;

#nullable disable

namespace Vendorea.PartnerConnect.Persistence.Migrations
{
    [DbContext(typeof(PartnerConnectDbContext))]
    [Migration("20260511180000_AddPriceFeedTables")]
    partial class AddPriceFeedTables
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.26")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            // Note: This is a partial model for the migration.
            // The full model is maintained in PartnerConnectDbContextModelSnapshot.cs
            // This migration adds PriceFeedUpload and SprPriceRecord entities.

            modelBuilder.Entity("Vendorea.PartnerConnect.Domain.Entities.PriceFeedUpload", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CorrelationId")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("DealerId")
                        .HasColumnType("int");

                    b.Property<int>("ErrorCount")
                        .HasColumnType("int");

                    b.Property<string>("ErrorMessage")
                        .HasMaxLength(4000)
                        .HasColumnType("nvarchar(4000)");

                    b.Property<string>("FileHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<long>("FileSizeBytes")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("ProcessedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("PushedToMerchant360At")
                        .HasColumnType("datetime2");

                    b.Property<int>("RecordCount")
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("StoragePath")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<int>("TradingPartnerId")
                        .HasColumnType("int");

                    b.Property<DateTime>("UploadedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("UploadedByUserId")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("DealerId");

                    b.HasIndex("FileHash");

                    b.HasIndex("Status");

                    b.HasIndex("TradingPartnerId");

                    b.HasIndex("UploadedAt");

                    b.HasIndex("DealerId", "TradingPartnerId", "FileHash")
                        .IsUnique();

                    b.HasIndex("DealerId", "TradingPartnerId", "UploadedAt");

                    b.ToTable("PriceFeedUploads", (string)null);
                });

            modelBuilder.Entity("Vendorea.PartnerConnect.Domain.Entities.SprPriceRecord", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<bool>("AutoProcureFromVendor")
                        .HasColumnType("bit");

                    b.Property<string>("BranchStockingStatus")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<bool>("BrokenQuantitiesAllowed")
                        .HasColumnType("bit");

                    b.Property<string>("CanShipUps")
                        .HasMaxLength(5)
                        .HasColumnType("nvarchar(5)");

                    b.Property<decimal>("CatalogListPrice")
                        .HasPrecision(12, 4)
                        .HasColumnType("decimal(12,4)");

                    b.Property<string>("CatalogPriceUom")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("CatalogUom")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("CategoryCode")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<decimal>("ConsumerPrice1")
                        .HasPrecision(12, 4)
                        .HasColumnType("decimal(12,4)");

                    b.Property<int>("ConsumerPrice1Quantity")
                        .HasColumnType("int");

                    b.Property<decimal>("ConsumerPrice2")
                        .HasPrecision(12, 4)
                        .HasColumnType("decimal(12,4)");

                    b.Property<int>("ConsumerPrice2Quantity")
                        .HasColumnType("int");

                    b.Property<decimal>("ConsumerPrice3")
                        .HasPrecision(12, 4)
                        .HasColumnType("decimal(12,4)");

                    b.Property<int>("ConsumerPrice3Quantity")
                        .HasColumnType("int");

                    b.Property<decimal>("ConsumerPriceInCatalog")
                        .HasPrecision(12, 4)
                        .HasColumnType("decimal(12,4)");

                    b.Property<string>("CountryOfOrigin")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("DealerId")
                        .HasColumnType("int");

                    b.Property<string>("FreightRestricted")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("FurnitureCatalogPage")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("GeneralLineCatalogPage")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("HarmonizedCode")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<decimal>("HeightInches")
                        .HasPrecision(10, 4)
                        .HasColumnType("decimal(10,4)");

                    b.Property<bool>("IsAlwaysNet")
                        .HasColumnType("bit");

                    b.Property<bool>("IsCustom")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDatedGoods")
                        .HasColumnType("bit");

                    b.Property<bool>("IsFirmCost")
                        .HasColumnType("bit");

                    b.Property<bool>("IsNetCost")
                        .HasColumnType("bit");

                    b.Property<bool>("IsNonReturnable")
                        .HasColumnType("bit");

                    b.Property<bool>("IsReadyToAssemble")
                        .HasColumnType("bit");

                    b.Property<bool>("IsRecycled")
                        .HasColumnType("bit");

                    b.Property<bool>("IsSpecialOrder")
                        .HasColumnType("bit");

                    b.Property<decimal>("LengthInches")
                        .HasPrecision(10, 4)
                        .HasColumnType("decimal(10,4)");

                    b.Property<int>("MinimumSellingQuantity")
                        .HasColumnType("int");

                    b.Property<string>("MinorityVendorFlag")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("MoorePrefixStockNumber")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("MpcNumber")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("MsdsRequired")
                        .HasMaxLength(5)
                        .HasColumnType("nvarchar(5)");

                    b.Property<decimal>("NetCostCcp3")
                        .HasPrecision(12, 4)
                        .HasColumnType("decimal(12,4)");

                    b.Property<decimal>("NetCostCcp4")
                        .HasPrecision(12, 4)
                        .HasColumnType("decimal(12,4)");

                    b.Property<decimal>("NetCostNonCcp")
                        .HasPrecision(12, 4)
                        .HasColumnType("decimal(12,4)");

                    b.Property<string>("NewItemNumber")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("NewModel")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("OldItemNumber")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("OldModel")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("PackedPerUom1")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("PackedPerUom2")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("PackedPerUom3")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<int>("PackingQuantity1")
                        .HasColumnType("int");

                    b.Property<int>("PackingQuantity2")
                        .HasColumnType("int");

                    b.Property<int>("PackingQuantity3")
                        .HasColumnType("int");

                    b.Property<string>("PackingUom1")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("PackingUom2")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("PackingUom3")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<int>("PriceFeedUploadId")
                        .HasColumnType("int");

                    b.Property<string>("PriceCodeIdentifier")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTime?>("PricingEndDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("PricingFlyerPage")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("PricingProgramCode")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("PricingProgramName")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime?>("PricingStartDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("ProductDescription")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("ProductStatus")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<bool>("ProjectNumberRequired")
                        .HasColumnType("bit");

                    b.Property<decimal>("PromoLevel1Cost")
                        .HasPrecision(12, 4)
                        .HasColumnType("decimal(12,4)");

                    b.Property<int>("PromoLevel1Quantity")
                        .HasColumnType("int");

                    b.Property<decimal>("PromoLevel2Cost")
                        .HasPrecision(12, 4)
                        .HasColumnType("decimal(12,4)");

                    b.Property<int>("PromoLevel2Quantity")
                        .HasColumnType("int");

                    b.Property<decimal>("PromoLevel3Cost")
                        .HasPrecision(12, 4)
                        .HasColumnType("decimal(12,4)");

                    b.Property<int>("PromoLevel3Quantity")
                        .HasColumnType("int");

                    b.Property<int>("QuantityPerSuom")
                        .HasColumnType("int");

                    b.Property<string>("RecommendedSubstitutions")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<decimal>("RetailListPrice")
                        .HasPrecision(12, 4)
                        .HasColumnType("decimal(12,4)");

                    b.Property<string>("RetailUnitOfMeasure")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<int>("RetailUnitsPerSuom")
                        .HasColumnType("int");

                    b.Property<string>("SellingUnitOfMeasure")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<int>("ShippingLeadTimeDays")
                        .HasColumnType("int");

                    b.Property<string>("ShippingLeadTimeDescription")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("SingleUsePlastic")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<int>("SourceLineNumber")
                        .HasColumnType("int");

                    b.Property<string>("SpecialFlyerCatalogPage")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("StockNumber")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("StockNumberStripped")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("UnitedPrefixStockNumber")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Upc")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("UpcCasePack")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int>("UpcCasePackFactor")
                        .HasColumnType("int");

                    b.Property<string>("UpcIntermediatePack")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int>("UpcIntermediatePackFactor")
                        .HasColumnType("int");

                    b.Property<string>("UpcRetailPack")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int>("UpcRetailPackFactor")
                        .HasColumnType("int");

                    b.Property<string>("VendorDropShipFlag")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<decimal>("WeightLbs")
                        .HasPrecision(10, 4)
                        .HasColumnType("decimal(10,4)");

                    b.Property<decimal>("WidthInches")
                        .HasPrecision(10, 4)
                        .HasColumnType("decimal(10,4)");

                    b.HasKey("Id");

                    b.HasIndex("PriceFeedUploadId");

                    b.HasIndex("DealerId", "CategoryCode");

                    b.HasIndex("DealerId", "StockNumber");

                    b.HasIndex("DealerId", "Upc");

                    b.ToTable("SprPriceRecords", (string)null);
                });

            modelBuilder.Entity("Vendorea.PartnerConnect.Domain.Entities.PriceFeedUpload", b =>
                {
                    b.HasOne("Vendorea.PartnerConnect.Domain.Entities.TradingPartner", "TradingPartner")
                        .WithMany()
                        .HasForeignKey("TradingPartnerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("TradingPartner");
                });

            modelBuilder.Entity("Vendorea.PartnerConnect.Domain.Entities.SprPriceRecord", b =>
                {
                    b.HasOne("Vendorea.PartnerConnect.Domain.Entities.PriceFeedUpload", "PriceFeedUpload")
                        .WithMany()
                        .HasForeignKey("PriceFeedUploadId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PriceFeedUpload");
                });
#pragma warning restore 612, 618
        }
    }
}
