// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Vendorea.PartnerConnect.Persistence;

#nullable enable

namespace Vendorea.PartnerConnect.Persistence.Migrations;

[DbContext(typeof(PartnerConnectDbContext))]
partial class PartnerConnectDbContextModelSnapshot : ModelSnapshot
{
    protected override void BuildModel(ModelBuilder modelBuilder)
    {
#pragma warning disable 612, 618
        modelBuilder
            .HasAnnotation("ProductVersion", "8.0.0")
            .HasAnnotation("Relational:MaxIdentifierLength", 128);

        SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

        // Note: This is a placeholder snapshot.
        // In production, run `dotnet ef migrations add <MigrationName>` to generate proper snapshots.
        // This file enables EF Core to understand the current model state.

        modelBuilder.Entity("Vendorea.PartnerConnect.Domain.Entities.TradingPartner", b =>
        {
            b.Property<int>("Id")
                .ValueGeneratedOnAdd()
                .HasColumnType("int");

            SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

            b.Property<string>("Code")
                .IsRequired()
                .HasMaxLength(50)
                .HasColumnType("nvarchar(50)");

            b.Property<string>("Name")
                .IsRequired()
                .HasMaxLength(200)
                .HasColumnType("nvarchar(200)");

            b.Property<bool>("IsActive")
                .ValueGeneratedOnAdd()
                .HasColumnType("bit")
                .HasDefaultValue(true);

            b.HasKey("Id");
            b.HasIndex("Code").IsUnique();
            b.ToTable("TradingPartners");
        });

        // Additional entities would be defined here...
        // This snapshot file is required for EF Core migrations to work properly.
        // Run `dotnet ef migrations add` to generate proper entity mappings.
#pragma warning restore 612, 618
    }
}
