<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <IsPackable>false</IsPackable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="FluentAssertions" Version="6.*" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Relational" Version="8.0.29" />
    <PackageReference Include="Microsoft.Extensions.Logging.Abstractions" Version="8.*" />
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="17.12.0" />
    <PackageReference Include="Npgsql.EntityFrameworkCore.PostgreSQL" Version="8.0.*" />
    <PackageReference Include="Testcontainers.PostgreSql" Version="3.*" />
    <PackageReference Include="xunit" Version="2.9.2" />
    <PackageReference Include="xunit.runner.visualstudio" Version="2.8.2" />
    <PackageReference Include="coverlet.collector" Version="6.0.2" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\Vendorea.PartnerConnect.Persistence\Vendorea.PartnerConnect.Persistence.csproj" />
    <ProjectReference Include="..\..\src\Vendorea.PartnerConnect.WorkerProcesses\Vendorea.PartnerConnect.WorkerProcesses.csproj" />
    <ProjectReference Include="..\..\src\Vendorea.PartnerConnect.Infrastructure\Vendorea.PartnerConnect.Infrastructure.csproj" />
    <ProjectReference Include="..\..\src\Vendorea.PartnerConnect.PartnerAdapters\Vendorea.PartnerConnect.PartnerAdapters.csproj" />
  </ItemGroup>

</Project>
