namespace Vendorea.PartnerConnect.Domain.Entities.Supplier;

/// <summary>
/// Acknowledgement received from a supplier for a purchase order.
/// A single PO may have multiple acknowledgements (initial, updates).
/// </summary>
public class SupplierOrderAcknowledgement
{
    public int Id { get; set; }

    /// <summary>
    /// Reference to the PartnerDocument containing this acknowledgement.
    /// </summary>
    public int? PartnerDocumentId { get; set; }

    /// <summary>
    /// The purchase order being acknowledged.
    /// </summary>
    public int SupplierPurchaseOrderId { get; set; }

    /// <summary>
    /// Trading partner that sent this acknowledgement.
    /// </summary>
    public int TradingPartnerId { get; set; }

    /// <summary>
    /// The customer's PO number being acknowledged.
    /// </summary>
    public string PoNumber { get; set; } = string.Empty;

    /// <summary>
    /// Supplier's order number.
    /// </summary>
    public string? SupplierOrderNumber { get; set; }

    /// <summary>
    /// Date/time the acknowledgement was generated by supplier.
    /// </summary>
    public DateTime AcknowledgementDate { get; set; }

    /// <summary>
    /// Overall acknowledgement status.
    /// </summary>
    public AcknowledgementStatus Status { get; set; }

    /// <summary>
    /// Expected ship date from supplier.
    /// </summary>
    public DateTime? ExpectedShipDate { get; set; }

    /// <summary>
    /// Expected delivery date.
    /// </summary>
    public DateTime? ExpectedDeliveryDate { get; set; }

    /// <summary>
    /// Number of line items in acknowledgement.
    /// </summary>
    public int LineCount { get; set; }

    /// <summary>
    /// Notes/messages from supplier.
    /// </summary>
    public string? Notes { get; set; }

    /// <summary>
    /// Whether this is the initial acknowledgement or an update.
    /// </summary>
    public bool IsUpdate { get; set; }

    /// <summary>
    /// Sequence number for multiple acknowledgements on same PO.
    /// </summary>
    public int Sequence { get; set; } = 1;

    /// <summary>
    /// Correlation ID for tracking.
    /// </summary>
    public string CorrelationId { get; set; } = Guid.NewGuid().ToString();

    /// <summary>
    /// When this record was received/created.
    /// </summary>
    public DateTime ReceivedAt { get; set; } = DateTime.UtcNow;

    // Navigation
    public PartnerDocument? PartnerDocument { get; set; }
    public SupplierPurchaseOrder? PurchaseOrder { get; set; }
    public TradingPartner? TradingPartner { get; set; }
    public ICollection<SupplierOrderAcknowledgementLine> Lines { get; set; } = new List<SupplierOrderAcknowledgementLine>();
}

/// <summary>
/// Overall acknowledgement status.
/// </summary>
public enum AcknowledgementStatus
{
    /// <summary>All lines accepted as ordered.</summary>
    Accepted = 0,

    /// <summary>Accepted with changes (quantity, date, substitution).</summary>
    AcceptedWithChanges = 10,

    /// <summary>Some lines accepted, some rejected/backordered.</summary>
    PartiallyAccepted = 20,

    /// <summary>Order rejected entirely.</summary>
    Rejected = 30,

    /// <summary>Pending review by supplier.</summary>
    Pending = 40,

    /// <summary>Order is on hold.</summary>
    OnHold = 50
}
